FROM node:lts
RUN mkdir /app
RUN chown node:node /app

RUN mkdir /app/node_modules
RUN chown node:node /app/node_modules

WORKDIR  /app

USER node

COPY --chown=node:node package.json ./
RUN npm install --quiet

COPY --chown=node:node . .
