### STAGE 1:BUILD ###
FROM node:lts-alpine AS build

# Create a Virtual directory inside the docker image

WORKDIR /app
# Copy files to virtual directory
# COPY package.json package-lock.json ./

RUN apk update && apk add bash

# Run command in Virtual directory
RUN npm cache clean --force

# Copy files from local machine to virtual directory in docker image
COPY . .
RUN npm install
RUN ng build --configuration production


### STAGE 2:RUN ###
# Defining nginx image to be used
FROM nginx:latest AS ngi

# Copying compiled code and nginx config to different folder
COPY --from=build /app/dist/ensys-gui-angular/browser /usr/share/nginx/html
COPY --from=build /app/dist/ensys-gui-angular/3rdpartylicenses.txt /usr/share/nginx/html/3rdpartylicenses.txt
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Exposing a port, here it means that inside the container
# the app will be using Port 80 while running
EXPOSE 8000