FROM node:lts

RUN mkdir /app
#RUN chown node:node /app

RUN mkdir /app/node_modules
#RUN chown node:node /app/node_modules

WORKDIR  /app

CMD ng s

#COPY --chown=node:node package.json package-lock.json ./
#package-lock.json
COPY package.json ./

RUN npm install angular --quiet

#COPY --chown=node:node . .
COPY . .

EXPOSE 4200
