services:
    db-dev:
        image: postgres:17-alpine
        container_name: ensys-dev-db
        env_file: .env
        restart: always
        networks:
            - local
        ports:
            - "5432:5432"
        volumes:
            - ./storage/db:/var/lib/postgresql/data

    frontend-dev:
        build:
            context: ./frontend
            dockerfile: docker/dockerfile.local
        container_name: ensys-dev-frontend
        env_file: .env
        command: sh -c "npm start"
        working_dir: /app
        restart: no
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules/
        ports:
            - "${PROXY_PORT_PROD}:4200"
        networks:
            - local
        depends_on:
            - db-dev

    backend-dev:
        build:
            context: backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-backend
        env_file: .env
        command: sh -c "alembic upgrade head && uvicorn app.main:fastapi_app --forwarded-allow-ips="*" --host 0.0.0.0 --port 8001"
        restart: no
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FASTAPI_PORT_PROD}:8001"
        networks:
            - local
        depends_on:
            - db-dev
            - flower-dev
            - celery-dev

    redis-dev:
        image: redis:alpine
        container_name: ensys-dev-redis
        restart: always
        env_file: .env
        command: [ "redis-server", "--bind", "redis-dev"]
        networks:
            - local
        volumes:
            - cache:/data

    celery-dev:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-celery
        env_file: .env
        command: celery --app=app.celery.celery_app worker --concurrency=4 -E -n docker-develop@localhost --loglevel=INFO
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
            - ${GUROBI_LICENSE_FILE_PATH}:/backend/gurobi.lic
        networks:
            - local
        depends_on:
            - redis-dev

    flower-dev:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-flower
        env_file: .env
        command: celery --app=app.celery.celery_app flower --port=8002
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FLOWER_PORT_PROD}:8002"
        networks:
            - local
        depends_on:
            - redis-dev

networks:
    local:

volumes:
    static_volume:
    node_modules:
    cache:
    grafana_storage:

