services:
    frontend-dev:
        build:
            context: ./frontend
            dockerfile: docker/dockerfile.dev
        container_name: ensys-dev-frontend
        env_file: .env
        restart: no
        networks:
            - ensys-dev

    backend-dev:
        build:
            context: backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-backend
        env_file: .env
        environment:
            - "POSTGRES_HOST=host.docker.internal"
        command: sh -c "alembic upgrade head && uvicorn app.main:fastapi_app --proxy-headers --forwarded-allow-ips="*" --host 0.0.0.0 --port 8001"
        restart: no
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        networks:
            - ensys-dev
        depends_on:
            - flower-dev
            - celery-dev

    redis-dev:
        image: redis:alpine
        container_name: ensys-dev-redis
        restart: always
        env_file: .env
        command: [ "redis-server", "--bind", "redis-dev", "--port", "${REDIS_PORT_DEV}" ]
        networks:
            - ensys-dev
        volumes:
            - cache_dev:/data

    celery-dev:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-celery
        env_file: .env
        command: celery --app=app.celery.celery_app worker --concurrency=4 -E -n docker-develop@localhost --loglevel=INFO
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
            - ${GUROBI_LICENSE_FILE_PATH}:/backend/gurobi.lic
        networks:
            - ensys-dev
        depends_on:
            - redis-dev

    flower-dev:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-dev-flower
        env_file: .env
        command: celery --app=app.celery.celery_app flower --port=8002
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FLOWER_PORT_DEV}:8002"
        networks:
            - ensys-dev
        depends_on:
            - redis-dev

    proxy-dev:
        build:
            context: ./proxy
            dockerfile: dev/dockerfile
        container_name: ensys-dev-proxy
        restart: always
        ports:
            - "${PROXY_PORT_DEV}:80"
        networks:
            - ensys-dev
            - ensys-network
        depends_on:
            - frontend-dev
            - backend-dev

networks:
    ensys-network:
        external: true
    ensys-dev:

volumes:
    cache_dev:
