services:
    db:
        image: postgres:17-alpine
        container_name: ensys-new-db
        env_file: .env.dev
        restart: always
        networks:
            - backend
        ports:
            -   "5432:5432"
        volumes:
            - ./storage/db:/var/lib/postgresql/data

    frontend:
        build:
            context: ./frontend
            dockerfile: docker/dockerfile.dev
        container_name: ensys-new-frontend
        env_file: .env.dev
        command: sh -c "npm start"
        working_dir: /app
        restart: no
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules/
        ports:
            - "${PROXY_PORT}:4200"
        networks:
            - frontend

    backend:
        build:
            context: backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-new-backend
        env_file: .env.dev
        command: sh -c "alembic upgrade head && uvicorn app.main:fastapi_app --forwarded-allow-ips="*" --host 0.0.0.0 --port 8001"
        restart: no
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FASTAPI_PORT}:8001"
        networks:
            - backend
        depends_on:
            - flower
            - celery

    redis:
        image: redis:alpine
        container_name: ensys-new-redis
        restart: always
        env_file: .env.dev
        command: [ "redis-server", "--bind", "redis", "--port", "${REDIS_PORT}" ]
        networks:
            - backend
        volumes:
            - cache:/data

    celery:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-new-celery
        env_file: .env.dev
        command: celery --app=app.celery.celery_app worker --concurrency=4 -E -n docker-develop@localhost --loglevel=INFO
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
            - ${GUROBI_LICENSE_FILE_PATH}:/backend/gurobi.lic
        networks:
            - backend
        depends_on:
            - redis

    flower:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-new-flower
        env_file: .env.dev
        command: celery --app=app.celery.celery_app flower --port=8002
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FLOWER_PORT}:8002"
        networks:
            - backend
        depends_on:
            - redis

networks:
    frontend:
    backend:

volumes:
    static_volume:
    node_modules:
    cache:
