services:
    frontend-prod:
        build:
            context: ./frontend
            dockerfile: docker/dockerfile.prod
        container_name: ensys-prod-frontend
        env_file: .env
        restart: no
        networks:
            - ensys-prod

    backend-prod:
        build:
            context: backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-prod-backend
        env_file: .env
        environment:
            - "POSTGRES_HOST=host.docker.internal"
        command: sh -c "alembic upgrade head && uvicorn app.main:fastapi_app --proxy-headers --forwarded-allow-ips="*" --host 0.0.0.0 --port 8001"
        restart: no
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        networks:
            - ensys-prod
        depends_on:
            - flower-prod
            - celery-prod

    redis-prod:
        image: redis:alpine
        container_name: ensys-prod-redis
        restart: always
        env_file: .env
        command: [ "redis-server", "--bind", "redis-prod", "--port", "${REDIS_PORT_PROD}" ]
        networks:
            - ensys-prod
        volumes:
            - cache_prod:/data

    celery-prod:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-prod-celery
        env_file: .env
        command: celery --app=app.celery.celery_app worker --concurrency=4 -E -n docker-develop@localhost --loglevel=INFO
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./backend/templates:/backend/templates
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
            - ${GUROBI_LICENSE_FILE_PATH}:/backend/gurobi.lic
        networks:
            - ensys-prod
        depends_on:
            - redis-prod

    flower-prod:
        build:
            context: ./backend
            dockerfile: docker/dockerfile
            args:
                os_version: ${OS_VERSION}
        container_name: ensys-prod-flower
        env_file: .env
        command: celery --app=app.celery.celery_app flower --port=8002
        volumes:
            - ./backend/app:/backend/app
            - ./backend/data:/backend/data
            - ./ensys:/backend/ensys
            - ${HOST_DATADIR}:${LOCAL_DATADIR}
        ports:
            - "${FLOWER_PORT_PROD}:8002"
        networks:
            - ensys-prod
        depends_on:
            - redis-prod

    proxy-prod:
        build:
            context: ./proxy
            dockerfile: prod/dockerfile
        container_name: ensys-prod-proxy
        restart: always
        ports:
            - "${PROXY_PORT_PROD}:80"
        networks:
            - ensys-prod
            - ensys-network
        depends_on:
            - frontend-prod
            - backend-prod

networks:
    ensys-network:
        external: true
    ensys-prod:

volumes:
    cache_prod:
