site_name: ensys-gui-new
site_url: https://github.com/in-RET/ensys-gui-new
site_author: in.RET

# Repository
repo_name: in-RET/ensys-gui-new
repo_url: https://github.com/in-RET/ensys-gui-new

plugins:
    - glightbox
markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - 'Home': index.md
    - 'Developer Doc Help': possibilities.md
    - 'Backend': backend/index.md
    - 'Ensys':
          - 'Home': ensys/index.md
          - 'Common':
                - 'Konfigurationscontainer': ensys/common/config.md
                - 'Modelbuilder': ensys/common/modelbuilder.md
          - 'Components':
                - 'Energysystem': ensys/components/energysystem.md
                - 'Bus': ensys/components/bus.md
                - 'Flow': ensys/components/flow.md
                - 'Sink': ensys/components/sink.md
                - 'Source': ensys/components/source.md
                - 'Storage': ensys/components/storage.md
                - 'Transformer': ensys/components/transformer.md
                - 'Investment': ensys/components/investment.md
                - 'NonConvex': ensys/components/nonconvex.md
                - 'Release Notes': ensys/release-notes.md
    - 'About': about.md

theme:
    name: material
    favicon: assets/favicon.svg
    logo: assets/favicon.svg
    icon:
        repo: fontawesome/brands/github
        admonition:
            <type>: material/alert-outline
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          accent: teal
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode


        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: teal
          accent: teal
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

    language: en
    features:
        - content.tabs.link
        - content.code.copy

extra:
    social:
        - icon: fontawesome/solid/envelope
          link: mailto:ensys@hs-nordhausen.de
    generator: true
copyright: Copyright &copy; 2025 Institut für regenerative Energietechnik
