FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install git libpq-dev gcc libc-dev libhdf5-dev
RUN apt-get -y install python3-h5py

RUN apt autoclean

COPY requirements.txt requirements.txt
COPY wrapper/dist/ensys-0.2a7-py3-none-any.whl ensys-0.2a7-py3-none-any.whl

RUN pip install --upgrade pip
RUN pip install ensys-0.2a7-py3-none-any.whl
RUN pip install -r requirements.txt

COPY app/ app/

COPY versions/ versions/
COPY env.py env.py
COPY alembic.ini alembic.ini
