"""added_currency_to_projects

Revision ID: 1f429e3807fa
Revises: de219238c45d
Create Date: 2025-05-07 11:31:27.875562

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f429e3807fa'
down_revision: Union[str, None] = 'de219238c45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components_template')
    op.add_column('projects', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'currency')
    op.create_table('components_template',
    sa.Column('oemof_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='components_template_pkey')
    )
    # ### end Alembic commands ###
