"""empty message

Revision ID: 7eb1c08f19d6
Revises: 009c6203e077
Create Date: 2025-10-07 10:19:51.175413

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7eb1c08f19d6'
down_revision: Union[str, None] = 'ec5474a7fbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('projects',
                  sa.Column('is_template', sa.Boolean(), nullable=False, default=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_template')
    # ### end Alembic commands ###
