"""empty message

Revision ID: ec5474a7fbd8
Revises: f8fb2db3099a
Create Date: 2025-09-15 12:45:20.596154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec5474a7fbd8'
down_revision: Union[str, None] = 'f8fb2db3099a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'unit_energy')
    op.drop_column('projects', 'currency')
    op.drop_column('projects', 'unit_co2')
    op.alter_column('scenarios', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('scenarios', 'time_steps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('scenarios', 'energysystem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('energysystem', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('scenarios', 'time_steps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scenarios', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('unit_co2', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('unit_energy', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
