"""Added units to projects and templates

Revision ID: 8ec2d87f9925
Revises: d656e290e0b6
Create Date: 2025-11-14 10:19:51.747853

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ec2d87f9925"
down_revision: Union[str, None] = "d656e290e0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "unit_currency", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "unit_energy", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "unit_co2", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
    )
    op.add_column(
        "templates",
        sa.Column(
            "unit_currency", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
    )
    op.add_column(
        "templates",
        sa.Column(
            "unit_energy", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
    )
    op.add_column(
        "templates",
        sa.Column(
            "unit_co2", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "unit_co2")
    op.drop_column("templates", "unit_energy")
    op.drop_column("templates", "unit_currency")
    op.drop_column("projects", "unit_co2")
    op.drop_column("projects", "unit_energy")
    op.drop_column("projects", "unit_currency")
    # ### end Alembic commands ###
