"""Added template description

Revision ID: cf31a52cf03f
Revises: 8ec2d87f9925
Create Date: 2025-11-26 13:54:55.296344

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf31a52cf03f"
down_revision: Union[str, None] = "8ec2d87f9925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "template_scenarios",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("template_scenarios", "description")
    # ### end Alembic commands ###
