"""added_template_flag

Revision ID: 009c6203e077
Revises: ec5474a7fbd8
Create Date: 2025-09-25 15:52:09.285925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '009c6203e077'
down_revision: Union[str, None] = 'ec5474a7fbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('is_template', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'is_template')
    # ### end Alembic commands ###
