"""Added date_created and date_updated to scenarios

Revision ID: 3135c8c0c0f3
Revises: cb7bfe6ee320
Create Date: 2026-06-23 12:52:20.765014

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3135c8c0c0f3'
down_revision: Union[str, None] = 'cb7bfe6ee320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('scenarios', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'date_updated')
    op.drop_column('scenarios', 'date_created')
    op.alter_column('projects', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=600),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
