"""Added constraints to templates

Revision ID: cb7bfe6ee320
Revises: c8c13c40725d
Create Date: 2026-05-28 15:33:45.935583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb7bfe6ee320'
down_revision: Union[str, None] = 'c8c13c40725d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_scenarios', sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_scenarios', 'constraints')
    # ### end Alembic commands ###
