"""added simulation year to scenarios and made end_date not nullable in simulations.

Revision ID: 461d624279a9
Revises: 1f429e3807fa
Create Date: 2025-05-08 16:06:59.903589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '461d624279a9'
down_revision: Union[str, None] = '1f429e3807fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('simulation_year', sa.Integer(), nullable=False, existing_type=sa.Integer(), server_default='2025'))
    op.alter_column('simulations', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('scenarios', 'simulation_year')
    # ### end Alembic commands ###
