"""remodel api

Revision ID: 52eaea8c0f93
Revises: 7171f7534e8b
Create Date: 2025-04-25 11:39:20.265628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pygments.lexer import using
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52eaea8c0f93'
down_revision: Union[str, None] = '7171f7534e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_in_design', sa.Column('position', sa.JSON(), nullable=True))
    op.drop_column('components_in_design', 'pos_x')
    op.drop_column('components_in_design', 'pos_y')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_in_design', sa.Column('pos_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('components_in_design', sa.Column('pos_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('components_in_design', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('components_in_design', 'position')
    # ### end Alembic commands ###
