"""modified components

Revision ID: 7171f7534e8b
Revises: 846f48d6db25
Create Date: 2025-04-15 11:22:07.180828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7171f7534e8b'
down_revision: Union[str, None] = '846f48d6db25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_in_design', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'components_in_design', 'scenarios', ['scenario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components_in_design', type_='foreignkey')
    op.drop_column('components_in_design', 'scenario_id')
    # ### end Alembic commands ###
