"""added components

Revision ID: 846f48d6db25
Revises: 596ec7663cce
Create Date: 2025-04-10 15:16:40.600057

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846f48d6db25'
down_revision: Union[str, None] = '596ec7663cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components_in_design',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('oemof_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('data', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    components_table = op.create_table('components_template',
    sa.Column('oemof_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('components')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(components_table, [
        {'oemof_type': 'Sink', 'fields': ['constraint_group', 'inputs', 'label', 'outputs']},
        {'oemof_type': 'Source', 'fields': ['constraint_group', 'inputs', 'label', 'outputs']},
        {'oemof_type': 'Converter', 'fields': ['constraint_group', 'inputs', 'label', 'outputs']},
        {'oemof_type': 'OffsetConverter', 'fields': ['constraint_group', 'inputs', 'label', 'normed_offset_and_conversion_factors_from_coefficients', 'outputs', 'plot_partload']},
        {'oemof_type': 'Bus', 'fields': ['balanced', 'constraint_group', 'custom_properties', 'inputs', 'label', 'outputs']},
        {'oemof_type': 'GenericStorage', 'fields': ['constraint_group', 'inputs', 'label', 'outputs']},
        {'oemof_type': 'Flow', 'fields': ['Label', 'age', 'bidirectional', 'custom_properties', 'fix', 'fixed_costs', 'flow', 'from_object', 'full_load_time_max', 'full_load_time_min', 'input', 'integer', 'investment', 'label', 'lifetime', 'max', 'min', 'negative_gradient_limit', 'nominal_value', 'nonconvex', 'output', 'positive_gradient_limit', 'values', 'variable_costs']},
        {'oemof_type': 'Investment', 'fields': ['age', 'ep_costs', 'existing', 'fixed_costs', 'interest_rate', 'lifetime', 'maximum', 'minimum', 'nonconvex', 'offset', 'overall_maximum', 'overall_minimum']},
        {'oemof_type': 'NonConvex', 'fields': ['activity_costs', 'first_flexible_timestep', 'inactivity_costs', 'initial_status', 'maximum_shutdowns', 'maximum_startups', 'minimum_downtime', 'minimum_uptime', 'negative_gradient_limit', 'positive_gradient_limit', 'shutdown_costs', 'startup_costs']}
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_table('components',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('oemof_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fields', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='components_pkey')
    )
    op.drop_table('components_template')
    op.drop_table('components_in_design')
    # ### end Alembic commands ###
