"""remodel data structure

Revision ID: 9d1f84384845
Revises: 21bc4f612e8e
Create Date: 2025-05-14 12:50:44.020637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1f84384845'
down_revision: Union[str, None] = '21bc4f612e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('interval', sa.Float(), nullable=False))
    op.add_column('scenarios', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('scenarios', sa.Column('time_steps', sa.Integer(), nullable=True))

    status_enum = postgresql.ENUM('STARTED', 'FINISHED', 'FAILED', 'CANCELED',  name='status', create_type=False)
    status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('scenarios', 'status', type_=status_enum, postgresql_using='status::status')
    op.drop_column('scenarios', 'timestep')
    op.drop_column('scenarios', 'user_mode')
    op.drop_column('scenarios', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scenarios', sa.Column('user_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('scenarios', sa.Column('timestep', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_column('scenarios', 'time_steps')
    op.drop_column('scenarios', 'start_date')
    op.drop_column('scenarios', 'interval')
    # ### end Alembic commands ###
