"""remodeled the scenario table

Revision ID: a46f39424133
Revises: 27323d40cd9f
Create Date: 2025-07-04 11:55:27.403305

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a46f39424133'
down_revision: Union[str, None] = '27323d40cd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('modeling_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenarios', sa.Column('energysystem', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('scenarios', 'energysystem_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios',
                  sa.Column('energysystem_model', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                            nullable=True))
    op.drop_column('scenarios', 'energysystem')
    op.drop_column('scenarios', 'modeling_data')
    # ### end Alembic commands ###
