"""Create a baseline migrations

Revision ID: d069500e8a0e
Revises: a9d4036237a7
Create Date: 2025-03-19 13:32:34.037148

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd069500e8a0e'
down_revision: Union[str, None] = 'a9d4036237a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('oemof_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('sim_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.alter_column('projects', 'country',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'country',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_column('projects', 'latitude')
    op.drop_column('projects', 'longitude')
    op.drop_table('simulations')
    op.drop_table('components')
    # ### end Alembic commands ###
