"""updated scenario schema

Revision ID: dac134a828f3
Revises: e139d12cbe94
Create Date: 2025-05-20 13:09:03.400923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac134a828f3'
down_revision: Union[str, None] = 'e139d12cbe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
