"""empty message

Revision ID: de219238c45d
Revises: 52eaea8c0f93
Create Date: 2025-04-29 11:11:40.375315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de219238c45d'
down_revision: Union[str, None] = '52eaea8c0f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components_in_design')
    op.alter_column('components_template', 'fields',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('scenarios', sa.Column('energysystem_model', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'energysystem_model')
    op.alter_column('components_template', 'fields',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.create_table('components_in_design',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('oemof_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name='components_in_design_scenario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='components_in_design_pkey')
    )
    # ### end Alembic commands ###
