"""cleanup scenario data

Revision ID: e139d12cbe94
Revises: 8981ad2b1fee
Create Date: 2025-05-20 12:04:35.594687

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e139d12cbe94'
down_revision: Union[str, None] = '8981ad2b1fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'simulation_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('simulation_year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
