FROM squidfunk/mkdocs-material

RUN pip install --no-cache-dir \
  mkdocs-git-revision-date-localized-plugin \
  mkdocs-glightbox \
  mkdocstrings \
  mkdocstrings-python

RUN mkdir Testfolder

ENTRYPOINT ["mkdocs"]